export const enum ERROR_MESSAGES {
  DEFAULT = "Error Occured!",
  TOAST_DEFAULT_TITLE = "Caution! Error Occured!",
  IMAGE_DELETED = "Failed to delete image",
  FETCHING_ASSETS = "Error while fetching assets!",
  UPLOADING_IMAGE = "Failed to upload image",
  FAILED_TO_GENERATE_PDF = "Failed to generate PDF content",
  INVALID_SEARCH_PARAMS = "Invalid Search Params! Please try again later.",
  INVOICE_NOT_FOUND = "Invoice not found! Please try again later.",
  BLOB_NOT_INITIALIZED = "Blob not initialized. Initialize the InvoiceDownloadManager",
  INVOICE_DATA_NOT_INITIALIZED = "Invoice data not initialized. Initialize the InvoiceDownloadManager",
  INVOICE_NAME_NOT_INITIALIZED = "Invoice name not initialized. Initialize the InvoiceDownloadManager",
  INVOICE_NOT_FOUND_OR_NO_PERMISSION = "Invoice not found or user does not have permission to delete it.",
  FAILED_TO_DELETE_INVOICE = "Failed to delete invoice from database.",
  FAILED_TO_INSERT_DATA = "Failed to insert data into database.",
  TRY_UPDATING_TO_DIFFERENT_STATUS = "Try updating to a different status. Current status is same as the new status.",
  FAILED_TO_CONVERT_CANVAS_TO_BLOB = "Failed to convert canvas to blob",
  FAILED_TO_GET_CANVAS_CONTEXT = "Failed to get canvas context",
  DATABASE_ERROR = "Database Error",
  FAILED_TO_EDIT_INVOICE = "Failed to edit invoice",
  NOT_ALLOWED_TO_SAVE_DATA = "Not allowed to save data. Please allow saving data in your account settings.",
  INDEXDB_ERROR = "IndexDB Error",
  NOT_ALLOWED_TO_DELETE_IMAGE = "You are not allowed to delete this image",
  MAX_IMAGES_REACHED = "You have reached the maximum number of images in your account! Try deleting some images.",
}
